"""add listing_views table

Revision ID: 717c799d0fc1
Revises: d15d4cde64bc
Create Date: 2026-07-15 09:58:29.294724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717c799d0fc1'
down_revision: Union[str, Sequence[str], None] = 'd15d4cde64bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_views_created_at'), 'listing_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_listing_views_id'), 'listing_views', ['id'], unique=False)
    op.create_index(op.f('ix_listing_views_listing_id'), 'listing_views', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_views_session_id'), 'listing_views', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_views_session_id'), table_name='listing_views')
    op.drop_index(op.f('ix_listing_views_listing_id'), table_name='listing_views')
    op.drop_index(op.f('ix_listing_views_id'), table_name='listing_views')
    op.drop_index(op.f('ix_listing_views_created_at'), table_name='listing_views')
    op.drop_table('listing_views')
    # ### end Alembic commands ###
